#!/bin/sh

if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

gnuplot<<EOF
    set terminal postscript eps color enhanced "Helveicta,20"
    set output "OF_vs_CHEMKINII.eps"
    set xlabel "Time / [s]" font "Helveicta,24"
    set ylabel "Temperature / [K]" font "Helveicta,24"
    set grid
    set key left top
    set xrange [0:0.07]
    set yrange [750:2750]
    set ytic 250
    plot \
        "19species.out" u 1:2 t "19-species reduced QSS mechanism" with points lt 1 pt 6 ps 1.5,\
        "30species.out" u 1:2 t "30-species skeletal mechanism" with lines lt -1
EOF

#------------------------------------------------------------------------------

